# This workflow will install Python dependencies, format, and build with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# USAGE: nothing will be run if commit message 

name: Build and Release Python App

on:
  push:
    branches: [ "main" ]

env:
  DO_RELEASE: ${{ contains(github.event.head_commit.message, '[RELEASE]') }}

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, '[NOBUILD]') }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Format with black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black clippy.py --verbose
        black setup.py --verbose
    - name: Build Installer
      run: |
        brew install create-dmg
        ./build.sh
    - name: Push installer
      run: |
        git add Clippy-Installer.dmg
        git commit -m "[WORKFLOW]: Build Python App"
        git push
  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release Tag
        if: ${{ env.DO_RELEASE == 'true' }}
        # !!! gets $VERSION_TAG from setup.py !!!
        run: |
          echo $VERSION_TAG
          git tag ${{ env.VERSION_TAG }}
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.dmg